export const PRODUCT_DETAILS_LOADING = "PRODUCT_DETAILS_LOADING";
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const ACTIVE_VERINT_PD_DETAILS = "ACTIVE_VERINT_PD_DETAILS";
export const CLEAR_ACTIVE_VERINT_PD_DETAILS = "CLEAR_ACTIVE_VERINT_PD_DETAILS";
